     shell /usr/bin/bash
          
     #modifier key
         kitty_mod ctrl+shift
         map kitty_mod+t launch --cwd=current --type=window
         map kitty_mod+enter launch --cwd=current --type=window

     # BEGIN_KITTY_THEME
     #Base2Tone Evening Dark
         include current-theme.conf
     #END_KITTY_THEME

     # Font configuration
         font_family 
         font_family      MesloLGS NF
         bold_font        auto
         italic_font      auto
         bold_italic_font auto
     
     font_size        10.7

     #transparancy
         background_opacity 0.7

     # WINDOWS
         window_margin_width 3
         single_window_margin_width 0

             # BACKGROUND
                 #background_image ~/Pictures/wm-dark.png
                 #background_image_layout scaled

     # WINDOW BORDER
         active_border_color #10f577
         inactive_border_color #3d2d2d
         window_border_width 1pt

     #layout 
         enabled_layouts tall,*

